name: sq1_assignment

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic-pull-request:
    uses: victorcovi/very_good_workflows/.github/workflows/semantic_pull_request.yml@main

  build:
    uses: victorcovi/very_good_workflows/.github/workflows/flutter_package.yml@main
    with:
      flutter_channel: stable
      min_coverage: 10

  spell-check:
    uses: victorcovi/very_good_workflows/.github/workflows/spell_check.yml@main
    with:
      includes: |
        **/*.md
      modified_files_only: false
