name: sq1_assignment

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  semantic-pull-request:
    uses: victorcovi/very_good_workflows/.github/workflows/semantic_pull_request.yml@main

  read-version:
    runs-on: ubuntu-latest
    outputs:
      flutter_version: ${{ steps.read_version.outputs.flutter_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - id: read_version
        name: Read Flutter version from .fvmrc
        run: echo "::set-output name=flutter_version::$(cat .fvmrc)"

  build:
    needs: read-version
    uses: victorcovi/very_good_workflows/.github/workflows/flutter_package.yml@main
    with:
      flutter_version: ${{ needs.read-version.outputs.flutter_version }}
      min_coverage: 10

  spell-check:
    uses: victorcovi/very_good_workflows/.github/workflows/spell_check.yml@main
    with:
      includes: |
        **/*.md
      modified_files_only: false
